# Generated by Django 3.2.9 on 2022-11-15 10:03

import core.models
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(help_text='Name for internal use.', max_length=128, unique=True)),
                ('image', models.FileField(upload_to='icons')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model, core.models.DisplayableModelMixin),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(help_text='Name for internal use.', max_length=128, unique=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model, core.models.DisplayableModelMixin),
        ),
    ]
