# Generated by Django 3.2.9 on 2022-11-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='sender',
        ),
    ]
