# Generated by Django 3.2.9 on 2022-12-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0002_auto_20221117_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(related_name='event_galleries', to='core.Image'),
        ),
    ]
