# Generated by Django 3.2.9 on 2022-12-06 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0003_alter_organisation_category'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('author', models.ForeignKey(help_text='Can be null if the author-user had been deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ManyToManyField(related_name='post_galleries', to='core.Image')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.image')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
