# Generated by Django 3.2.9 on 2022-11-15 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(choices=[('country', 'Country'), ('county', 'County'), ('town', 'Town')], max_length=32)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.icon')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
