# Generated by Django 3.2.9 on 2022-12-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('country', 'Country'), ('county', 'County'), ('town', 'Town'), ('state', 'State')], max_length=32),
        ),
    ]
