# Generated by Django 3.2.9 on 2022-12-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20221117_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='category',
            field=models.CharField(choices=[('church', 'Church'), ('job', 'Job'), ('music', 'Music'), ('news', 'News'), ('non-profit', 'Non-profit'), ('public service', 'Public service'), ('school', 'School'), ('sports', 'Sports'), ('volunteeringbusiness', 'Volunteeringbusiness')], max_length=32),
        ),
    ]
